apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ipfixcat-env
configMapGenerator:
- name: ipfixcat-env
  env: env.properties
namespace: default
resources:
- deployment.yaml
- service.yaml
- secrets/secrets.yaml

